version: '3.9'

services:
    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        container_name: bundle_client
        restart: always
        volumes:
            - ./client:/usr/src/app
        ports:
            - '3000:3000'
        depends_on:
            - api
        environment:
            - NEXT_PUBLIC_SERVER_ENDPOINT=http://localhost:5000
    api:
        build:
            context: ./api
            dockerfile: Dockerfile
        container_name: bundle_api
        restart: always
        volumes:
            - ./api:/usr/src/app
        ports:
            - '5000:5000'
